pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import qs.modules.common
import "paper_plates_data.js" as PlateData

/**
 * The plate on the wall — the paper family's desktop picture.
 *
 * A *plate* is one public-domain engraving, chart, map or woodblock reduced to
 * ink density in a PNG's alpha channel: black pixels, no paper of its own. That
 * is what lets a single asset serve all three variants and both modes —
 * PaperBackground lays the plate on the variant's `paper` token and tints it
 * with the variant's `ink`, so a live variant switch re-inks the picture with no
 * reload, exactly like every other token in the family.
 *
 * The collection lives in assets/images/paper-plates and is catalogued in
 * paper_plates_data.js; both are generated by scripts/paper/fetch_plates.py.
 *
 * ONE PLATE PER DAY. The pick is a pure function of the local date, so:
 *   - every screen and every surface agrees on today's picture without anyone
 *     sharing state,
 *   - it survives a shell reload (a random pick would change on every reload,
 *     which reads as a bug, not as a feature),
 *   - it changes at local midnight — the clock below ticks hourly and the date
 *     rolls the index over.
 *
 * Pin one plate with `Config.options.paper.backdrop.plate` (a file name from the
 * catalog) to stop the rotation; clear it to resume. `next()`/`previous()` pin as
 * they step, which is how you flick through the collection to look at it:
 *
 *   qs -c ii ipc call paperPlate next
 *   qs -c ii ipc call paperPlate daily
 */
Singleton {
    id: root

    // ------------------------------------------------------------------ config

    /// Draw a plate at all. False leaves the bare paper ground of the old design.
    readonly property bool enabled: Config.options?.paper?.backdrop?.enable ?? true
    /// A catalog file name ("hokusai-great-wave.png"), or "" for the daily pick.
    readonly property string pinned: Config.options?.paper?.backdrop?.plate ?? ""
    /// User multiplier on the variant's base opacity, for a heavier or fainter
    /// wall without touching the theme.
    readonly property real strength: Config.options?.paper?.backdrop?.strength ?? 1.0

    // ----------------------------------------------------------------- the pick

    readonly property int count: PlateData.count()

    /// Hourly is enough to catch midnight, and cheap: SystemClock only wakes on
    /// the boundary it is asked for.
    SystemClock {
        id: clock
        precision: SystemClock.Hours
        enabled: root.enabled
    }

    /// Whole days since the epoch in LOCAL time — the day counter the catalog
    /// indexes by. Local, so the picture turns over at the user's midnight and
    /// not at UTC's.
    readonly property int day: {
        const now = clock.date;
        if (!now)
            return 0;
        return Math.floor((now.getTime() - now.getTimezoneOffset() * 60000) / 86400000);
    }

    /// Today's plate, or the pinned one. Null when disabled or the collection is
    /// empty — every consumer must handle that.
    readonly property var plate: {
        if (!root.enabled || PlateData.count() === 0)
            return null;
        if (root.pinned.length > 0) {
            const wanted = PlateData.byFile(root.pinned) ?? PlateData.byFile(root.pinned + ".png");
            if (wanted)
                return wanted;
            // A pin naming a plate that no longer exists must not blank the
            // desktop — fall through to the day's pick.
        }
        return PlateData.forDay(root.day);
    }

    readonly property url source: root.plate ? Qt.resolvedUrl(Quickshell.shellPath(`assets/images/paper-plates/${root.plate.file}`)) : ""

    /// "bleed" fills the screen; "motif" is a print laid on the sheet.
    readonly property string layout: root.plate?.layout ?? "bleed"
    readonly property string align: root.plate?.align ?? "center"
    readonly property real plateScale: root.plate?.scale ?? 0.92
    readonly property real aspect: root.plate?.aspect ?? 1.72

    /// What PaperBackground draws the plate at: the variant's base weight, the
    /// plate's own correction, and the user's multiplier.
    readonly property real inkOpacity: root.plate ? PaperTheme.backdrop.plateOpacity * (root.plate.weight ?? 1.0) * root.strength : 0

    /// "Hokusai, The Great Wave — 1831" for a credit line; empty when there is
    /// no plate. Nothing draws this today; it exists because a picture on the
    /// wall should be able to say what it is.
    readonly property string credit: {
        if (!root.plate)
            return "";
        const parts = [root.plate.artist, root.plate.title].filter(p => p && p.length > 0);
        const line = parts.join(", ");
        return root.plate.date ? `${line} — ${root.plate.date}` : line;
    }

    // ------------------------------------------------------------------ actions

    function pin(file: string): void {
        if (PlateData.byFile(file) || PlateData.byFile(`${file}.png`))
            Config.options.paper.backdrop.plate = file;
    }

    /// Back to the plate of the day.
    function daily(): void {
        Config.options.paper.backdrop.plate = "";
    }

    function step(by: int): void {
        if (PlateData.count() === 0)
            return;
        const here = PlateData.plates.indexOf(root.plate);
        const next = ((here < 0 ? 0 : here + by) % PlateData.count() + PlateData.count()) % PlateData.count();
        Config.options.paper.backdrop.plate = PlateData.plates[next].file;
    }

    function next(): void {
        root.step(1);
    }

    function previous(): void {
        root.step(-1);
    }

    /// Dial the whole wall up or down. 1.0 is the variant's own weight; the
    /// range is deliberately generous (a plate can be turned into a full
    /// wallpaper or down to a ghost) and clamped only against nonsense.
    function setStrength(value: real): void {
        Config.options.paper.backdrop.strength = Math.max(0, Math.min(4, value));
    }

    function heavier(): void {
        root.setStrength(root.strength + 0.1);
    }

    function lighter(): void {
        root.setStrength(root.strength - 0.1);
    }
}
