.pragma library
/*
 * Backdrop plate catalog for the "paper" panel family.
 *
 * Auto-generated by scripts/paper/fetch_plates.py — do not edit by hand; edit
 * the PLATES list in that script and re-run it.
 *
 * Every entry names a PNG in assets/images/paper-plates/ that carries ink
 * density in its alpha channel and nothing else. PaperBackground lays it on the
 * variant's `paper` and tints it with the variant's `ink`, so one asset serves
 * all three variants in both light and dusk, and re-tints live on a switch.
 *
 *   file    basename under assets/images/paper-plates/
 *   layout  "bleed" fills the screen | "motif" is a print laid on the sheet
 *   align   motif placement: "center" | "left" | "right"
 *   scale   motif height as a fraction of screen height
 *   weight  per-plate opacity multiplier, on top of the variant's base opacity
 *   aspect  width / height, so a surface can lay a plate out before it loads
 *   title / artist / date / licence / source — provenance, all public domain
 *
 * PaperPlates.qml is what surfaces should use; it picks the plate of the day
 * out of this list.
 */
var plates = [
    {
        file: "hokusai-great-wave.png",
        layout: "bleed",
        align: "center",
        scale: 0.92,
        weight: 0.997,
        aspect: 1.7204,
        title: "Japanese: 『神奈川沖浪裏』 - Kanagawa oki nami ura The Great Wave Off the Coast of Kanagawa",
        artist: "Katsushika Hokusai",
        date: "from 1830 until 1832",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Katsushika_Hokusai_-_Thirty-Six_Views_of_Mount_Fuji-_The_Great_Wave_Off_the_Coast_of_Kanagawa_-_Google_Art_Project.jpg"
    },
    {
        file: "hokusai-tama-river.png",
        layout: "bleed",
        align: "center",
        scale: 0.92,
        weight: 1.019,
        aspect: 1.7204,
        title: "冨嶽三十六景 武州玉川",
        artist: "Katsushika Hokusai",
        date: "circa 1830",
        licence: "CC0",
        source: "https://commons.wikimedia.org/wiki/File:%E5%86%A8%E5%B6%BD%E4%B8%89%E5%8D%81%E5%85%AD%E6%99%AF_%E6%AD%A6%E5%B7%9E%E7%8E%89%E5%B7%9D-Fuji%E2%80%94The_Tama_River,_Musashi_Province,_from_the_series_Thirty-six_Views_of_Mount_Fuji_(Fugaku_sanj%C5%ABrokkei)_MET_DP140975.jpg"
    },
    {
        file: "hokusai-hodogaya.png",
        layout: "bleed",
        align: "center",
        scale: 0.92,
        weight: 1.014,
        aspect: 1.7204,
        title: "冨嶽三十六景 東海道保土ケ谷",
        artist: "Katsushika Hokusai",
        date: "circa 1830",
        licence: "CC0",
        source: "https://commons.wikimedia.org/wiki/File:%E5%86%A8%E5%B6%BD%E4%B8%89%E5%8D%81%E5%85%AD%E6%99%AF_%E6%9D%B1%E6%B5%B7%E9%81%93%E4%BF%9D%E5%9C%9F%E3%82%B1%E8%B0%B7-Hodogaya_on_the_T%C5%8Dkaid%C5%8D_(T%C5%8Dkaid%C5%8D_Hodogaya),_from_the_series_Thirty-six_Views_of_Mount_Fuji_(Fugaku_sanj%C5%ABrokkei)_MET_DP141025.jpg"
    },
    {
        file: "cellarius-christian-constellations.png",
        layout: "bleed",
        align: "center",
        scale: 0.92,
        weight: 0.986,
        aspect: 1.7204,
        title: "1660 celestial chart representing the constellations according to Christian symbolism",
        artist: "Andreas Cellarius",
        date: "1660",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:1660_celestial_chart_representing_the_constellations_according_to_Christian_symbolism.jpg"
    },
    {
        file: "ortelius-tartary.png",
        layout: "bleed",
        align: "center",
        scale: 0.92,
        weight: 0.98,
        aspect: 1.7204,
        title: "Tartary from Theatrum orbis terrarum, by Abraham Ortelius",
        artist: "Abraham Ortelius",
        date: "1579",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Tartary_from_Theatrum_orbis_terrarum,_by_Abraham_Ortelius.jpg"
    },
    {
        file: "ortelius-flandria.png",
        layout: "bleed",
        align: "center",
        scale: 0.92,
        weight: 0.965,
        aspect: 1.7204,
        title: "Theatrum orbis terrarum - Flandria",
        artist: "Abraham Ortelius",
        date: "2019-02-20",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Theatrum_orbis_terrarum_-_Flandria.jpg"
    },
    {
        file: "piranesi-sawhorse.png",
        layout: "bleed",
        align: "center",
        scale: 0.92,
        weight: 0.966,
        aspect: 1.7204,
        title: "The Sawhorse, from Carceri d'invenzione (Imaginary Prisons)",
        artist: "Giovanni Battista Piranesi",
        date: "circa 1749",
        licence: "CC0",
        source: "https://commons.wikimedia.org/wiki/File:The_Sawhorse,_from_Carceri_d%27invenzione_(Imaginary_Prisons)_MET_DP828186.jpg"
    },
    {
        file: "encyclopedie-plate-2-087.png",
        layout: "motif",
        align: "center",
        scale: 0.94,
        weight: 0.59,
        aspect: 1.1747,
        title: "Encyclopedie volume 2-087",
        artist: "",
        date: "",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Encyclopedie_volume_2-087.png"
    },
    {
        file: "encyclopedie-plate-4-295.png",
        layout: "motif",
        align: "center",
        scale: 0.92,
        weight: 0.55,
        aspect: 1.2539,
        title: "Encyclopedie volume 4-295",
        artist: "",
        date: "",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Encyclopedie_volume_4-295.png"
    },
    {
        file: "encyclopedie-plate-5-241.png",
        layout: "motif",
        align: "center",
        scale: 0.92,
        weight: 0.751,
        aspect: 1.1782,
        title: "Encyclopedie volume 5-241",
        artist: "",
        date: "",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Encyclopedie_volume_5-241.png"
    },
    {
        file: "haeckel-discomedusae.png",
        layout: "motif",
        align: "center",
        scale: 0.94,
        weight: 0.999,
        aspect: 0.6969,
        title: "Haeckel Discomedusae 8",
        artist: "Original: Ernst Haeckel . Scan: Ragesoss . Cleanup: Ilmari Karonen",
        date: "1904",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Haeckel_Discomedusae_8.jpg"
    },
    {
        file: "haeckel-siphonophorae.png",
        layout: "motif",
        align: "center",
        scale: 0.94,
        weight: 1.004,
        aspect: 0.7169,
        title: "Haeckel Siphonophorae",
        artist: "Ernst Haeckel",
        date: "1904",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Haeckel_Siphonophorae.jpg"
    },
    {
        file: "haeckel-echinidea.png",
        layout: "motif",
        align: "center",
        scale: 0.94,
        weight: 0.773,
        aspect: 0.8206,
        title: "Echinidea. - Igelsterne LCCN2015648942",
        artist: "Giltsch, Adolf, 1852-1911, lithographer; Haeckel, Ernst, 1834-1919, artist",
        date: "1904",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Echinidea._-_Igelsterne_LCCN2015648942.jpg"
    },
    {
        file: "haeckel-acephala.png",
        layout: "motif",
        align: "center",
        scale: 0.94,
        weight: 1.009,
        aspect: 0.6706,
        title: "Acephala. - Muscheln LCCN2014645038",
        artist: "Giltsch, Adolf, 1852-1911, lithographer; Haeckel, Ernst, 1834-1919, artist",
        date: "1904",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Acephala._-_Muscheln_LCCN2014645038.jpg"
    },
    {
        file: "haeckel-orchidae.png",
        layout: "motif",
        align: "center",
        scale: 0.94,
        weight: 1.02,
        aspect: 0.7163,
        title: "Haeckel Orchidae",
        artist: "Ernst Haeckel",
        date: "1904",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Haeckel_Orchidae.jpg"
    },
    {
        file: "audubon-carolina-parrot.png",
        layout: "motif",
        align: "center",
        scale: 0.92,
        weight: 1.006,
        aspect: 0.7525,
        title: "26 Carolina Parrot",
        artist: "John James Audubon",
        date: "between 1827 and 1838",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:26_Carolina_Parrot.jpg"
    },
    {
        file: "redoute-rosa-muscosa.png",
        layout: "motif",
        align: "center",
        scale: 0.9,
        weight: 1.002,
        aspect: 0.5869,
        title: "RosaMuscosa Alba-Rosier-mousseux-a-fleurs-blanches",
        artist: "Pierre-Joseph Redouté",
        date: "1817",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:RosaMuscosa_Alba-Rosier-mousseux-a-fleurs-blanches.jpg"
    },
    {
        file: "redoute-rosa-centifolia.png",
        layout: "motif",
        align: "center",
        scale: 0.9,
        weight: 1.001,
        aspect: 0.6756,
        title: "Rosa centifolia Burgundiaca",
        artist: "Pierre-Joseph Redouté",
        date: "1824",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Rosa_centifolia_Burgundiaca.jpg"
    },
    {
        file: "merian-surinam-plate-1.png",
        layout: "motif",
        align: "center",
        scale: 0.92,
        weight: 1.002,
        aspect: 0.7137,
        title: "Metamorphosis insectorum surinamensium (Pl. 1) BHL41398750",
        artist: "Merian, Maria Sibylla",
        date: "1705",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Metamorphosis_insectorum_surinamensium_(Pl._1)_BHL41398750.jpg"
    },
    {
        file: "merian-surinam-plate-7.png",
        layout: "motif",
        align: "center",
        scale: 0.92,
        weight: 1.001,
        aspect: 0.755,
        title: "Metamorphosis insectorum surinamensium (Pl. 7) BHL41398732",
        artist: "Merian, Maria Sibylla",
        date: "1705",
        licence: "Public domain",
        source: "https://commons.wikimedia.org/wiki/File:Metamorphosis_insectorum_surinamensium_(Pl._7)_BHL41398732.jpg"
    }
];

/// The number of plates in the collection.
function count() {
    return plates.length;
}

/**
 * The plate for a given day. `day` is a whole number of days — any monotonic
 * day counter works; PaperPlates feeds it days-since-epoch, so the picture
 * changes at local midnight and every screen agrees on it.
 *
 * The stride is a step of 7 through the list rather than a hash: with 7 and a
 * collection whose size is not a multiple of it, consecutive days land far
 * apart in the list (so yesterday's Haeckel is not followed by another Haeckel)
 * while every plate still comes up exactly once per full cycle.
 */
function forDay(day) {
    if (plates.length === 0)
        return null;
    var stride = (plates.length % 7 === 0) ? 5 : 7;
    return plates[Math.abs(Math.floor(day) * stride) % plates.length];
}

/// Look a plate up by its `file` name, for a pinned pick. Null when unknown.
function byFile(file) {
    for (var i = 0; i < plates.length; i++) {
        if (plates[i].file === file)
            return plates[i];
    }
    return null;
}
